name: Deploy on DigitalOcean Droplet
on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get image name from docker-compose.yml
        id: image-name
        uses: KJ002/read-yaml@main
        with:
          file: '../../docker-compose.yml'
          key-path: '["services", "server", "image"]'
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: IMAGE_NAME, REGISTRY, {{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}, GITHUB_SHA
          script: |
            # login to dockerhub
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
            # stop old images
            docker kill $(docker ps -q)
            # pull updated image
            docker pull ${{ steps.image-name.outputs.data }}
            # # Run new container
            # docker run -d \
            # -- restart always \
            # --name $(echo $IMAGE_NAME) \
            # $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
